language: python
python:
  - "2.7"
  - "3.6"
env:
  - NUMPY_VERSION=1.16.9
  - NUMPY_VERSION=1.16.10
# command to install dependencies, requirements.txt should NOT include numpy
install:
  - pip install -r requirements.txt numpy==$NUMPY_VERSION
# command to run tests
script:
  - pytest
